### Numpy


Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of Numpy, focusing on arrays and vectorized operations

In [1]:
!pip install numpy

/home/muhammadi/Desktop/Machine Learnning/bootcamp/venv/bin/pip: 2: exec: /home/muhammadi/Desktop/Udemy AL/bootcamp/venv/bin/python3: not found


In [4]:
import numpy as np 

## create array using numpy
## create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
# 1D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [7]:
## 2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [12]:
np.arange(0,10,2)
np.reshape(5,1)

array([5])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
## Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
## Attributes of Numpy

arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape) # Output: (2,3)
print("Number of Dimentions:", arr.ndim) # Output: 2
print("Size (number of elements):", arr.size) # Output: 6
print("Data type:", arr.dtype) # Output: int64 (may vary based on platform)
print("Item size (in bytes):",arr.itemsize) # Output: 8


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimentions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [18]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

### Element Wise Subtraction
print("Subtraction:", arr1-arr2)

### Element Wise Multiplication
print("Multiplication:", arr1*arr2)

### Element Wise Division
print("Division:", arr1/arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [19]:
## Universal Function
arr=np.array([2,3,4,5,6])

## Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## Natural Log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [20]:
# array slicing and indexing
arr=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [26]:
print(arr[0][0])
print(arr[0:2])

1
[[1 2 3 4]
 [4 5 6 7]]


In [27]:
print(arr[1:,2:])

[[ 6  7]
 [ 9 10]]


In [28]:
print(arr[0:2,2:])

[[3 4]
 [6 7]]


In [29]:
## Modify array elements
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  4   5   6   7]
 [  7   8   9  10]]


In [30]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [34]:
# Logical Operations
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])